### PR TITLE
add a 'chunked' iterator, Header --> HashMap, make cigar_len() public

### PR DESCRIPTION
**Pull request by pmarks**
Various API additions that we've found useful.

### CODE REVIEW

**Comment by pmarks** [comment]
@johanneskoester - requested changes made. I tested with regex 0.2 - 1.0. since that's a common crate, does it make sense to try a support a wider version range?

**Comment by johanneskoester** [comment]
Don't know. Do you know an example where this has been done?

**Comment by pmarks** [comment]
I don't see any mention of it here: https://rust-lang-nursery.github.io/api-guidelines/checklist.html

but given that it compiles w/ versions up to 1.0, we might as well have it be >=0.2

**Comment by johanneskoester** [comment]
Why not just switching to 1.0. that should be fine.

**Comment by johanneskoester** [comment]
That should be not a problem, as rust compiles stuff statically. It might just increase the binary size, because the regex crate is compiled in twice.

**Comment by johanneskoester** [comment]
I think your commit is not yet pushed?

**Comment by pmarks** [comment]
@johanneskoester - sorry, this dropped off my radar.  I think this is ready now.

**Pull request merged**
