### PR TITLE
refactor: move source into subfolder

### PR DESCRIPTION
**Pull request by johanneskoester**
This hopefully helps to make release please happy

### CODE REVIEW

**Comment by johanneskoester** [comment]
@brainstorm could you help me fixing the musl build here? I am unsure why it fails now. (the changes here seem to be needed to make release-please happy).

**Comment by brainstorm** [comment]
Hey @johanneskoester! From what I've learned with my journey with Rust and lambdas, [MUSL is now discouraged](https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306#discussioncomment-490301), so I'd actually drop that target in favor of just using the native ones.

Also: less code, less breakage ;)

**Comment by johanneskoester** [comment]
> Hey @johanneskoester! From what I've learned with my journey with Rust and lambdas, [MUSL is now discouraged](https://github.com/awslabs/aws-lambda-rust-runtime/discussions/306#discussioncomment-490301), so I'd actually drop that target in favor of just using the native ones... do we know any specific user/org using rust-htslib w/ MUSL?
> 
> Also: less code, less breakage ;)

ok, will do!

**Comment by johanneskoester** [comment]
Closing this as it has diverged too much from main branch.

**Pull request closed without merging**
