### PR TITLE
Change `read` API to Option<Result<()>>

### PR DESCRIPTION
**Pull request by slazicoicr**

### CODE REVIEW

**Comment by brainstorm** [comment]
@dlaehnemann @slazicoicr @TyberiusPrime (and everyone) what shall we do about this PR and https://github.com/rust-bio/rust-htslib/issues/162 overall? :)

**Comment by TyberiusPrime** [comment]
Since the recent hackaton is basically all breaking changes on "fetch" any way
(you have to change fetch(chr, start, stop) to fetch((chr, start, stop)), 
we might as well get this in the same release.

Option<Result<_> is what an iterator would return (internally) - I think it's appropriate.

Side note: 
I've mostly prepared one more PR that replaces all 'fetch, then iterate' APIs with 'fetch-and-iterate' ones (basically the missing part of #163),but it's not ready yet (and I'm sitting at the wrong machine this morning), and it's orthogonal to the return type of read().

**Comment by dlaehnemann** [comment]
So I guess, we merge this and then at least wait for this last PR by @TyberiusPrime before a new release. And maybe check again, if there is more breaking stuff that could go in -- while we are at it...

**Review by dlaehnemann — APPROVED** [review]
LGTM

**Comment by dlaehnemann** [comment]
I'd say this is ready to merge, but after I meddled so much, maybe someone else wants to quickly scan the code and merge? @brainstorm ;)

**Comment by brainstorm** [comment]
Thanks much for this @slazicoicr !

**Pull request merged**
