### PR TITLE
Update/lib samtools example

### PR DESCRIPTION
**Pull request by vsoch**
It took me a while to figure out where exactly the docs are, and how they are generated, but finally I did! This is a small PR that adds an example to generate the same output with rust-htslib as you would with samtools to inspect a header (discussed in https://github.com/rust-bio/rust-htslib/issues/244#issuecomment-684108611). I'll also add some notes to give perspective from a relatively new user exploring the library.

## Setup
If you are a seasoned rustacean, it's obvious that you'd have a project, and know how to interact with cargo. if you are a bioscientist coming to the repository and not familiar with rust, it's a little bit more challenging to get started. I realized that in order to even test small snippets of code, I'd need to install rust-htslib (documentation I found in the README, and I was caught up a bit by not doing the `--recursive` clone to get the entire thing) and then figuring out how to create a sample project, e.g.,

```bash
$ tree rust-htslib-example/ -L 1
rust-htslib-example/
├── Cargo.lock
├── Cargo.toml
├── data
├── README.md
├── src
└── target

3 directories, 3 files
```
This gave me enough to be able to copy snippets from the docs, and try things out. I also installed samtools with conda. I suspect that a very new user would not just be provided these docs (which are for specific functions and source code) but would have a tutorial to walk them through the entire process? I'm curious about the intended audience for the documentation, and how new folks will be gently introduced.

## Looking at the header / bam classes
Are these called classes? Structures (or I see Struct)? Something else? I knew that my goal was to reproduce the samtools output but with rust-htslib - a user familiar with samtools would appreciate seeing this from the getgo. I first tried looking at the current code to loop through the records of the bam (not the header):

```rust
use rust_htslib::{bam, bam::Read};

fn main() {

    let mut bam = bam::Reader::from_path(&"data/test.bam").unwrap();
    let header = bam::Header::from_template(bam.header());

    // copy reverse reads to new BAM file
    for r in bam.records() {
        let record = r.unwrap();
        if record.is_reverse() {
            println!("{:?}", &record.inner);
        }
    }
}
```
That prints out quite a bit, and although it could be that something could be mapped from there to the samtools output, I suspect not - this is likely records in the bam file, and not the header

```bash
    Finished dev [unoptimized + debuginfo] target(s) in 1.21s
     Running `target/debug/rust-htslib-example`
bam1_t { core: bam1_core_t { pos: 1, tid: 0, bin: 4681, qual: 1, l_extranul: 2, flag: 16, l_qname: 4, n_cigar: 3, l_qseq: 100, mtid: -1, mpos: -1, isize: 0 }, id: 0, data: 0x55bb6db58010, l_data: 196, m_data: 256, _bitfield_1: __BindgenBitfieldUnit { storage: [0, 0, 0, 0], align: [] }, __bindgen_padding_0: 0 }
bam1_t { core: bam1_core_t { pos: 1, tid: 0, bin: 4681, qual: 1, l_extranul: 0, flag: 16, l_qname: 12, n_cigar: 3, l_qseq: 100, mtid: -1, mpos: -1, isize: 0 }, id: 0, data: 0x55bb6db58010, l_data: 204, m_data: 256, _bitfield_1: __BindgenBitfieldUnit { storage: [0, 0, 0, 0], align: [] }, __bindgen_padding_0: 0 }
bam1_t { core: bam1_core_t { pos: 1, tid: 0, bin: 4681, qual: 1, l_extranul: 0, flag: 16, l_qname: 4, n_cigar: 3, l_qseq: 100, mtid: -1, mpos: -1, isize: 0 }, id: 0, data: 0x55bb6db58010, l_data: 196, m_data: 256, _bitfield_1: __BindgenBitfieldUnit { storage: [0, 0, 0, 0], align: [] }, __bindgen_padding_0: 0 }
bam1_t { core: bam1_core_t { pos: 1, tid: 0, bin: 4681, qual: 40, l_extranul: 1, flag: 16, l_qname: 4, n_cigar: 3, l_qseq: 100, mtid: -1, mpos: -1, isize: 0 }, id: 0, data: 0x55bb6db58010, l_data: 196, m_data: 256, _bitfield_1: __BindgenBitfieldUnit { storage: [0, 0, 0, 0], align: [] }, __bindgen_padding_0: 0 }
bam1_t { core: bam1_core_t { pos: 1, tid: 0, bin: 4681, qual: 1, l_extranul: 2, flag: 16, l_qname: 4, n_cigar: 3, l_qseq: 100, mtid: -1, mpos: -1, isize: 0 }, id: 0, data: 0x55bb6db58010, l_data: 196, m_data: 256, _bitfield_1: __BindgenBitfieldUnit { storage: [0, 0, 0, 0], align: [] }, __bindgen_padding_0: 0 }
```

I decided this isn't what I want, and explored the header instead. First I just printed it.

```rust
fn main() {

    let mut bam = bam::Reader::from_path(&"data/test.bam").unwrap();
    let header = bam::Header::from_template(bam.header());

    println!("{:?}", header)
}
```
 I see a list of records.

```
    Finished dev [unoptimized + debuginfo] target(s) in 1.18s
     Running `target/debug/rust-htslib-example`
Header { records: [[64, 83, 81, 9, 83, 78, 58, 67, 72, 82, 79, 77, 79, 83, 79, 77, 69, 95, 73, 9, 76, 78, 58, 49, 53, 48, 55, 50, 52, 50, 51, 10, 64, 83, 81, 9, 83, 78, 58, 67, 72, 82, 79, 77, 79, 83, 79, 77, 69, 95, 73, 73, 9, 76, 78, 58, 49, 53, 50, 55, 57, 51, 52, 53, 10, 64, 83, 81, 9, 83, 78, 58, 67, 72, 82, 79, 77, 79, 83, 79, 77, 69, 95, 73, 73, 73, 9, 76, 78, 58, 49, 51, 55, 56, 51, 55, 48, 48, 10, 64, 83, 81, 9, 83, 78, 58, 67, 72, 82, 79, 77, 79, 83, 79, 77, 69, 95, 73, 86, 9, 76, 78, 58, 49, 55, 52, 57, 51, 55, 57, 51, 10, 64, 83, 81, 9, 83, 78, 58, 67, 72, 82, 79, 77, 79, 83, 79, 77, 69, 95, 86, 9, 76, 78, 58, 50, 48, 57, 50, 52, 49, 52, 57]] }
```

As a new user, what I next do is look at the source code to see what public functions are available. I found the function `to_hashmap`:

```rust
use rust_htslib::{bam, bam::Read};

fn main() {

    let mut bam = bam::Reader::from_path(&"data/test.bam").unwrap();
    let header = bam::Header::from_template(bam.header());

    println!("{:?}", header.to_hashmap());

}
```
which looks promising! It mirrors what is found in the samtools output: 

```
warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1.41s
     Running `target/debug/rust-htslib-example`
{"SQ": [{"SN": "CHROMOSOME_I", "LN": "15072423"}, {"SN": "CHROMOSOME_II", "LN": "15279345"}, {"SN": "CHROMOSOME_III", "LN": "13783700"}, {"SN": "CHROMOSOME_IV", "LN": "17493793"}, {"SN": "CHROMOSOME_V", "LN": "20924149"}]}
```
Then it came down to realizing that the hashmap above has one key (SQ) which is a list of other maps, and I just needed to format the print to be the same as samtools (with an @ and then tab delimited).

```
@SQ	SN:CHROMOSOME_I	LN:15072423
@SQ	SN:CHROMOSOME_II	LN:15279345
@SQ	SN:CHROMOSOME_III	LN:13783700
@SQ	SN:CHROMOSOME_IV	LN:17493793
@SQ	SN:CHROMOSOME_V	LN:20924149
```
And that's the PR here! Very simple, and hopefully the walkthrough above can shed insight for what might be important for a user (I suspect the main developers here are experts with rust and forget what it's like to be a new person). I left the other examples as is. I can definitely act as tester / documentation updater for other snippets if someone wants to point them out.

I had started other work (for the previous issue) and wound up not using the branch, hence the commits seen here. Is it okay with the maintainers here to do a squash and merge to clean up the commit history, or should I be more careful in the future and do rebase?

### CODE REVIEW

**Comment by brainstorm** [comment]
Woah, @vsoch, that's an excellent doc PR, thanks a ton for this! :D

I really like the walk through in the PR description (coming from a first-time user) as well as the simplicity of the PR itself :)

I assume that users of this lib might already have an understanding of some of the concepts, but it's brilliant that you managed to describe it simply without being distracting or redundant for "seasoned" users, kudos to that!

**Review by brainstorm — CHANGES_REQUESTED** [review]
On [`src/lib.rs`](https://github.com/rust-bio/rust-htslib/blob/master/src/lib.rs#L17) I would now tweak the example below this one since it seems to contain an unnecessary bam header reading that is not explained (nor used)?:

```rust
//! let mut bam = bam::Reader::from_path(&"test/test.bam").unwrap();
//! let header = bam::Header::from_template(bam.header());                                                             <-----
//! let mut out = bam::Writer::from_path(&"test/out.bam", &header, bam::Format::BAM).unwrap();
```

**Comment by vsoch** [comment]
@brainstorm I had originally thought that too, but it's it still referenced via the `out` variable?
```rust
//! let mut out = bam::Writer::from_path(&"test/out.bam", &header, bam::Format::BAM).unwrap();
    this guy ----------------------------------------------^
```
I'm guessing that takes a reference from a header to write the new file. Would it help to add some text about this so it doesn't appear unused?

**Comment by brainstorm** [comment]
Ahh, gotcha, didn't notice that one, good catch! Nah, I think it's ok to leave it like that ;)

**Review by brainstorm — APPROVED** [review]

**Comment by brainstorm** [comment]
Thanks @vsoch! You are killing it! ;)

**Pull request merged**
