### PR TITLE
feat: Index for `bam::IndexedReader`

### PR DESCRIPTION
**Pull request by tedil**
This PR addresses issue #386 by providing a struct `IndexView` analogous to `HeaderView`.

Since I'm not particularly well versed in interfacing with C and the htslib API, I'm a bit unsure if this is "the correct way" to handle this. There's no corresponding implementation for `Clone` yet, and I'm not sure what the point of the `owned` field of `HeaderView` is, since it does not seem to be modified anywhere.

~~This still needs some testcases, a simple one should be the one from the referenced issue.~~

### CODE REVIEW

**Comment by tedil** [comment]
This currently only works for BAM + bai, not CRAM + crai, unsure why that is.

**Comment by tedil** [comment]
Ah, the cram index does not contain the necessary information, so the slow idxstats variant has to be used, see [bam_index.c](https://github.com/samtools/samtools/blob/556c60fdff977c0e6cadc4c2581661f187098b4d/bam_index.c#L140-L150) for more information

**Comment by tedil** [comment]
I've added an unpolished translation of the slow_idxstats method from [samtools bam_index.c](https://github.com/samtools/samtools/blob/556c60fdff977c0e6cadc4c2581661f187098b4d/bam_index.c#L140-L199), which should be used in case of CRAM (and SAM) indexed files.

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Nice work! If I remember correctly, the owned flag was for destroying the header view, which is not always what you want. But I don't recall the details anymore and don't have the time to check the code. However, this one looks good to me for now.

**Pull request merged**
