### PR TITLE
adding check and test to read sam file to close #251

### LINKED ISSUE #251: Cannot open SAM file with bam::Reader
It forces the file format to be BAM or CRAM.

### PR DESCRIPTION
**Pull request by vsoch**
This will add a check to allow for reading a sam file, along with a test! It's my first pull request in rust so I'm pretty stoked, albeit the fact that I didn't do much at all :)

I don't use VSCode normally so I haven't checked out the rust-analyzer plugin, but will do so tomorrow (err later today, just passed midnight). This will close #251, and I'll address any warnings / errors that come up!

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
Interesting, this test was spotty for me locally too:
```
failures:

---- bam::tests::test_http_connect stdout ----
Err(
    Open {
        target: "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/exome_alignment/HG00096.chrom11.ILLUMINA.bwa.GBR.exome.20120522.bam",
    },
)
thread 'bam::tests::test_http_connect' panicked at 'called `Result::unwrap()` on an `Err` value: Open { target: "http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/data/HG00096/exome_alignment/HG00096.chrom11.ILLUMINA.bwa.GBR.exome.20120522.bam" }', src/bam/mod.rs:1912:19


failures:
    bam::tests::test_http_connect
```
I'm going to try a re-run.

**Comment by vsoch** [comment]
It also seems like Octocat has been replaced by some sort of smiling Sanrio character... it must be Halloween soon! :jack_o_lantern:  :) 
image

**Comment by brainstorm** [comment]
@vsoch Working on it, hang in there, you'll get green soon, sorry for the confusion ;)

**Comment by vsoch** [comment]
No worries, I'm having fun! :)

**Pull request merged**
