### PR TITLE
fix: Loosen acceptable types to support current linux build on aarch64

### PR DESCRIPTION
**Pull request by rdeaton-freenome**
Fixes https://github.com/rust-bio/rust-htslib/issues/412

### CODE REVIEW

**Comment by ghuls** [comment]
Same for `ppc64le`.

**Review by johanneskoester — COMMENTED** [review]
aarch64 does not support i8?

**Comment by ghuls** [comment]
@johanneskoester I assume it is because of this: https://abstractexpr.com/2023/04/30/the-anomaly-of-the-char-type-in-c/

**Comment by rdeaton-freenome** [comment]
That article is spot on, it is fundamentally because the signedness of char is different across platforms. There are definitely better ways to fix this long term, but luckily the range of values here is so small that taking half of the i8 range is sufficient. Thanks!

**Pull request merged**
