### PR TITLE
Fix configuration when cross-compiling

### LINKED ISSUE #259: MUSL build fails on OSX
Hello, 

I have been trying `cargo build` on  `rust-htslib`:
```
$ git clone --recursive https://github.com/rust-bio/rust-htslib.git
$ cd rust-htslib 
$ cargo build
```
which output a whole lot warning on the c source code and a fatal
```
    error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/hts-sys-bf3eaa6abc104e1b/out/htslib" "-I" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/libz-sys-7c94d09687ec3ebf/out/include" "-I" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/bzip2-sys-1b34115e67e42ca9/out/include" "-I" "/Users/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/lzma-sys-0.1.16/xz-5.2/src/liblzma/api" "-I" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/curl-sys-6886d1c85d5521de/out/include" "-Wall" "-Wextra" "-o" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/hts-sys-bf3eaa6abc104e1b/out/htslib/sam.o" "-c" "/Users/admin/Desktop/MGHA_bioinformatics/PROJECT_rust_bio/rust-htslib/target/debug/build/hts-sys-bf3eaa6abc104e1b/out/htslib/sam.c" with args "cc" did not execute successfully (status code exit code: 1).
```

I have also tried
```
$ brew install FiloSottile/musl-cross/musl-cross
$ brew install bzip2 zlib xz curl-openssl
$ cross build
```
with the same result. 

However, `cross build --target x86_64-unknown-linux-musl` does work. 

Other info: 
* OS: MacOS Catalina 10.15.6 
* 
```
$ cc --version
Apple clang version 12.0.0 (clang-1200.0.31.1)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### PR DESCRIPTION
**Pull request by jmarshall**
Even when cross-compiling, _build.rs_ runs on the build host. Hence within _build.rs_ [`#[cfg(target_os)]` always reflects the host](https://kazlauskas.me/entries/writing-proper-buildrs-scripts.html), not the target. Use [`$CARGO_CFG_TARGET_OS`](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts) instead to query target properties.

Fixes #259.

### CODE REVIEW

**Comment by brainstorm** [comment]
Thanks John! Could you provide some documentation and/or comments alongside as you did on twitter? Also it seems like formatting is off.

**Review by brainstorm — CHANGES_REQUESTED** [review]
Just a `cargo fmt` away, simples ;)

**Comment by jmarshall** [comment]
The change is described in the commit message; beyond that, I don't know what documentation you're after.

I am not a rust developer and I am unfamiliar with your expected formatting. Moreover, I am not a rust-htslib user and I am not keen to devote further time to this. I would suggest that the maintainers are best placed to make any adjustments required should they choose to merge this bug fix.

**Comment by jmarshall** [comment]
Comment added, assuming what you were after was a comment in the source itself to further dissuade anyone naively reverting this to `#[cfg(target_os …)]`.

**Comment by brainstorm** [comment]
CI seemed to be stuck picking old commit messages, even with correctly formatted with `fix: <message>` as indicated in https://www.conventionalcommits.org/en/v1.0.0/#summary.

Anyway, thanks John for the contribution.

**Pull request merged**
