### PR TITLE
small tweaks I missed in thread pool PR

### PR DESCRIPTION
**Pull request by pmarks**

### CODE REVIEW

**Comment by brainstorm** [comment]
My apologies for merging too fast on this one, @pmarks :-S

**Comment by pmarks** [comment]
> My apologies for merging too fast on this one, @pmarks :-S

no problem!

**Comment by brainstorm** [comment]
@pmarks Does it makes sense to fix this coverage?:

https://coveralls.io/builds/32974892/source?filename=src%2Ftpool.rs

**Comment by pmarks** [comment]
> @pmarks Does it makes sense to fix this coverage?:
> 
> https://coveralls.io/builds/32974892/source?filename=src%2Ftpool.rs

I thought about it but I don't see a good way to force the thread pool creation to fail...

**Pull request merged**
