### PR TITLE
feat: implement htslib basemod api

### PR DESCRIPTION
**Pull request by jts**
This is a rebased implementation of the htslib basemod API that was originally in PR https://github.com/rust-bio/rust-htslib/pull/374. 

It relies on changes in https://github.com/rust-bio/hts-sys/pull/3 which will need to be merged first, and a new release made so Cargo.toml can be updated.

cc: @johanneskoester

### CODE REVIEW

**Review by johanneskoester — APPROVED** [review]

**Comment by johanneskoester** [comment]
Very nice and clean work! Thanks a lot!

**Comment by jts** [comment]
@johanneskoester is there anything else that needs to be done before this is merged?

**Comment by dlaehnemann** [comment]
Could you run `cargo fmt` on the branch, so that the `CI / Formatting` step is happy? As for the linting failures, I'm not sure. Maybe merging in the `master` branch already helps, as the `CI / Linting` step seems to have passed on other more recent branches.

With tests passing, I'd be glad to merge this!

**Comment by jts** [comment]
Thanks @dlaehnemann, I have updated the PR to fix the format errors (using `cargo fmt` as you suggested) and the linter warning. The remaining build errors are because https://github.com/rust-bio/hts-sys/pull/3 needs to be merged and released first, because this PR depends on new bindings.

**Comment by dlaehnemann** [comment]
The new `hts-sys` version is released, so I took the liberty of updating the version in Cargo.toml. Hope that's alright for you.

**Comment by dlaehnemann** [comment]
A CI issue is still holding up the release of the newer version, but this should be resolved soon:
https://github.com/rust-bio/hts-sys/pull/5

**Comment by jts** [comment]
Thanks for working on this (and for updating Cargo.toml) - let me know if you need any help from me

**Comment by dlaehnemann** [comment]
Hmm, now it [throws a doctest-failure](https://github.com/rust-bio/rust-htslib/actions/runs/5268190931/jobs/9524524323?pr=385#step:6:362):

```
---- src/bam/record.rs - bam::record::Record::basemods_iter (line 1025) stdout ----
error[E0425]: cannot find value `record` in this scope
Error:  --> src/bam/record.rs:1026:19
  |
3 | if let Ok(mods) = record.basemods_iter() {
  |                   ^^^^^^ not found in this scope
```

Probably something you can quickly fix, @jts ?

**Comment by jts** [comment]
Hm, it seems doctest doesn't like having my example code snippet. I'll see if there's an easy fix, otherwise I'll take the example out.

**Comment by dlaehnemann** [comment]
Could you instead just initialize a `record` here? If you think this bloats the example, you could always [hide parts of the doctest code](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#hiding-portions-of-the-example) that is run.

It would be a shame not to use this doctest...

**Comment by dlaehnemann** [comment]
This generally looks good, now. Would you feel comfortable and could you find the time to introduce more (doc)-tests?

Not sure how accurate the coveralls report is, but it suggests 92 new code lines uncovered by tests:
https://coveralls.io/builds/60751874

**Comment by dlaehnemann** [comment]
Ah, and I updated the PR with a change that the previous doctest failure suggested. So before any further changes, a resync with the remote branch probably avoids any conflicts.

**Comment by jts** [comment]
Sure, I won't be able to get to it today but will try to add some more tests tomorrow.

**Comment by jts** [comment]
@dlaehnemann I just pushed a commit to see how much of the new code it covers, I'll add more tests if needed later

**Comment by jts** [comment]
Hmm it seems that doctests aren't counted in the code coverage. Do you know whether that is the case? If so I'll write some proper tests

**Comment by dlaehnemann** [comment]
It's using [`tarpaulin`](https://github.com/xd009642/tarpaulin) with [the flag `--all-features` set](https://github.com/rust-bio/rust-htslib/blob/e89538d5a9971c6508ac38d92ac468f3d70241aa/.github/workflows/rust.yml#L71). From what I can see, this should also include doctests. But I guess the doctest only covers certain code paths? So maybe [unit tests with `mod tests`](https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html) also make sense for more systematic testing?

**Comment by jts** [comment]
I might be misinterpreting the coveralls report but the doctest should go down one code path that is reported as uncovered. No worries though, I'll write some `mod tests` now instead

**Comment by tedil** [comment]
> > I might be misinterpreting the coveralls report but the doctest should go down one code path that is reported as uncovered. No worries though, I'll write some `mod tests` now instead
> 
> Thanks for checking this, and it's unfortunate that coveralls / tarpaulin don't seem to take the doctests into account, here. But `mod tests` are a good idea anyways!

I think with the [current configuration of tarpaulin](https://github.com/rust-bio/rust-htslib/blob/e89538d5a9971c6508ac38d92ac468f3d70241aa/.github/workflows/rust.yml#L71), doc tests aren't considered at all.
Here's some information/discussion on the choice of parameters needed for tarpaulin to include those: https://github.com/xd009642/tarpaulin/issues/1302

**Comment by dlaehnemann** [comment]
Ah, thanks for this pointer. I was looking for info like this in the docs and didn't find it. Sounds like we might fix it by adding the `--doc --examples` flags to our tarpaulin command. Although I am not sure how exactly `--all-features` (as opposed to the `--all-targets` mentioned in the issue) handles doctests...

**Comment by dlaehnemann** [comment]
Looking great, now! Ready to merge, @jts ?

**Comment by dlaehnemann** [comment]
Well, thanks for all the work!

BTW, I am now trying to get tarpaulin / coveralls to also report on the doctests, over in PR #397.

**Pull request merged**
