### PR TITLE
Let buffer return Arc.

### PR DESCRIPTION
**Pull request by johanneskoester**

### CODE REVIEW

**Comment by brainstorm** [comment]
Isn't `Arc` more expensive than `Rc`? Why is this needed? :)

**Comment by johanneskoester** [comment]
This way, it is possible to easily parallelize computations on the returned Records. Other options would be to make this somehow optional, or wrap the Rc in an Arc for parallel computations. Do you have a feeling how much overhead it adds?

**Comment by veldsla** [comment]
Quick search yields this:
https://www.reddit.com/r/rust/comments/6x4bhg/how_slow_is_arc_relative_to_rc/

Seems to have a non trivial impact, but a benchmark might be more informative. Not something to casually throw in though.

**Comment by johanneskoester** [comment]
I think you are right. Better let the caller decide. I'll close this for now.

**Pull request closed without merging**
